services:
  # Denteeth API Service
  api:
    build: .
    image: denteeth-api:latest
    container_name: denteeth-api
    restart: unless-stopped
    env_file: .env
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - denteeth-network

  webserver:
    image: nginx:latest
    container_name: denteeth-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - denteeth-network
    ports:
      - "9000:80"
  
  # network
networks:
  denteeth-network:
    driver: bridge