services:
  # Denteeth API Service
  api:
    build: .
    image: denteeth-api:latest
    container_name: denteeth-api
    restart: unless-stopped
    env_file: .env
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - './storage:/var/www/html/storage'
    networks:
      - denteeth-network
  
  # network
networks:
  denteeth-network:
    driver: bridge